### PR TITLE
Content Update: who should attend section 

### PR DESCRIPTION
**Pull request by edakturk14**
lmk what you think, I have added the same line to all - it made the sections a bit too long but the line is important imo: "Engage with industry experts, listen to their career journeys, and explore the opportunities within the ecosystem." 

We can also remove this from each but have it on the top instead.

### CODE REVIEW

**Comment by kuzdogan** [comment]
Thanks!

Hmm it's a little difficult to read tbh. I would've just scrolled through this section. The font is not helping either. 

Should we separate it into bullets in such form, and emphasize the keywords?


### Who should attend?

`<Students> <Developers> ...`

### What to expect?

- Discover how to create **decentralized applications** and **smart contracts**

- Network with other developers and the Ethereum community

- Engage with industry experts, listen to their **career journeys**, and explore the **opportunities** within the ecosystem

If we agree on it, I need to change the formatting to accommodate bullet points and bold

We should try to keep it short and concise, especially for the mobile version. ChatGPT can help here :)

**Comment by edakturk14** [comment]
Thank you!

I like the bullet point idea + also tried to minimize the content and now it looks much better. Made a quick change on english content to show how it looks.

Put the last line only on anyone curious: "Engage with industry experts, listen to their career journeys, and explore the opportunities within the ecosystem." seemed better.

If we agree I'll update the TR content and emphasize some of the words as you mentioned as well. 

We can go with bullet points too if you'd prefer that instead. In that case, I'll add this line to all of the options. However since we want to keep less words this lgtm.

**Comment by kuzdogan** [comment]
Changed the layout. Check out the deploy preview

**Comment by edakturk14** [comment]
Updated the TR content to match the EN. It's also shorter while giving the message imo. 

Looks good to me! Thanks

**Comment by kuzdogan** [comment]
I did two things:
- [ ] Edited the CTAs **in Turkish**. I think now it's more to the point and specific. Please have a look. If we decide it's final, I can translate to English
- [ ] Added a list of topics **in Turkish**. I think it's nice to show what topics will be discussed (and what are not i.e. trading). Would also be nice if this sparks some curiosity in website visitors and they Google the terms.

**Comment by edakturk14** [comment]
1. I like the TR.
- Nit pick with one comment: the finance prof one is too long. (Suggestion to merge the last two sentence, boyle mesela:
Blokzincir teknolojisinin finansal potansiyeli ve Ethereum'un iç finansal modellerini keşfedin. )

2. I think this section looks a bit too crowded. Suggestion that they can be the same font as the speaker name for example and only have 2 lines of subjects. We could also remove for now and then add it later once we start building the schedule.

**Comment by kuzdogan** [comment]
Yes, let me actually remove the 3rd line on Finance Professionals. It sounds a little wordplay. The part I want to convey more is the last sentence.

**Pull request merged**
